### ISSUE TITLE
release

### ISSUE THREAD

**Issue by xmclark** [jasonsjones/singly-linked-list#2]
This package hasn't had a release in a while. 

I use this package in a project, and it currently brings along all of lodash. I believe the one loadash dependency was isolated recently, so the package size got a lot smaller, but it's not in npm yet. 

I think a 2.8 or a 2.7.1 release would be really nice!

**Comment by jasonsjones** [comment]
Oh yes, that would definitely be nice to update the release with the recent work...not sure why I didn't do it before 😉   Thank you for filing this issue!  Done.  Version 0.2.8 just published npm.

**Comment by xmclark** [comment]
Hey thank you so much for the quick response! I sincerely appreciate it. Have a wonderful Friday.
