### ISSUE TITLE
Feature request: Add array as parameter to enable instatiating with initial values

### ISSUE THREAD

**Issue by Dommar92** [jasonsjones/singly-linked-list#3]
Feature request: 
Add array as parameter to enable instatiating with initial values

let arr = ['a', 'b', 'c']
let list = new LinkedList(arr);
// arr === list.toArray()

**Comment by jasonsjones** [comment]
Yes, I think this would be a very beneficial feature to have--thank you for opening the issue.  In fact, I think I had this in mind to do, but got distracted with other 'shiny objects' and hadn't gotten to it yet.

And I see you have submitted a PR as well...I'll take a look.  Thanks again 👍

**Comment by jasonsjones** [comment]
Closed with #5331ac71d219802f0ca981acbed664a6d2bb3f08
